echo "######### STARTING ##########"
go run client.go testuser ../testfile.txt &
go run client.go testuser ../testfile.txt &
go run client.go testuser ../testfile.txt &
go run client.go testuser ../testfile.txt & 
go run client.go testuser ../testfile.txt &
go run client.go mstack ../testfile.txt &
go run client.go mstack ../testfile.txt &
go run client.go mstack ../testfile.txt &
go run client.go mstack ../testfile.txt & 
go run client.go testuser ../testfile.txt &
go run client.go testuser ../testfile.txt &
go run client.go testuser ../testfile.txt &
go run client.go mstack ../testfile.txt &
go run client.go mstack ../testfile.txt & 
go run client.go testuser ../testfile.txt &
go run client.go testuser ../testfile.txt &
go run client.go testuser ../testfile.txt &
go run client.go testuser ../testfile.txt &
go run client.go testuser ../testfile.txt & 
go run client.go testuser ../testfile.txt &
go run client.go mstack ../testfile.txt &
go run client.go mstack ../testfile.txt &
go run client.go mstack ../testfile.txt &
go run client.go mstack ../testfile.txt & 
go run client.go testuser ../testfile.txt &
go run client.go testuser ../testfile.txt &
go run client.go testuser ../testfile.txt &
go run client.go mstack ../testfile.txt &
go run client.go mstack ../testfile.txt & 
go run client.go testuser ../testfile.txt &
go run client.go testuser ../testfile.txt &
go run client.go testuser ../testfile.txt &
go run client.go testuser ../testfile.txt &
go run client.go testuser ../testfile.txt & 
go run client.go testuser ../testfile.txt &
go run client.go mstack ../testfile.txt &
go run client.go mstack ../testfile.txt &
go run client.go mstack ../testfile.txt &
go run client.go mstack ../testfile.txt & 
go run client.go testuser ../testfile.txt &
go run client.go testuser ../testfile.txt &
go run client.go testuser ../testfile.txt &
go run client.go mstack ../testfile.txt &
go run client.go mstack ../testfile.txt & 
go run client.go testuser ../testfile.txt &
go run client.go testuser ../testfile.txt &
go run client.go testuser ../testfile.txt &
go run client.go testuser ../testfile.txt &
go run client.go testuser ../testfile.txt & 
go run client.go testuser ../testfile.txt &
go run client.go mstack ../testfile.txt &
go run client.go mstack ../testfile.txt &
go run client.go mstack ../testfile.txt &
go run client.go mstack ../testfile.txt & 
go run client.go testuser ../testfile.txt &
go run client.go testuser ../testfile.txt &
go run client.go testuser ../testfile.txt &
go run client.go mstack ../testfile.txt &
go run client.go mstack ../testfile.txt & 
go run client.go testuser ../testfile.txt &
echo "######### DONE ##########"